### ISSUE TITLE
[Figure 2] Illustrating lambda scheme figure [help]

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/alchemical-best-practices#38]
As one of the figures I wanted a clear conceptual figure that explains how the lambda switching works, but using a concrete example to make it easier to understand. I also wanted to make a connection to thinking of it in terms of probability distributions to then make the concept of overlap easier to understand later on. 

Below is my first pass at this figure. I would appreciate any comments, or suggestions for improvements. 

[Fig2.pdf](https://github.com/michellab/alchemical-best-practices/files/3879111/Fig2.pdf)

**Comment by mrshirts** [comment]
One issue is that too many colors are changing, indicating that more things are changing than should be.  The "solvent" is changing color (blue to orange), but also the chemical moiety.  It might be better if the part of the chemical that is present in A was the color of the distribution in B, with the solvent remaining the same. 

I think there does need to be x and y labels on the distributions.  The question is what the x axis, which is not always easy to summarize for a complex transformation.  Literally, you want configurations sampled Hamiltonian lambda_i be visited by configurations sampled by Hamiltonian lambda i+1 and lambda i-1.  But collapsing all the configurations down to a single coordinate is as always challenging (unless one is dealing with harmonic oscillators or something).  So maybe it's just P(\xi), where \xi is defined in the caption as a generalized coordinate capturing the overall configuration space change.  But it is NOT P(\lambda) . . .   
  
One other thing that could be useful for visualizing changing lambda is a graph of U(r,lambda) for, say, the softcore Lennard-Jones transformation, something like this:
![image](https://user-images.githubusercontent.com/4274132/69426954-a9923280-0ceb-11ea-91b3-4288f8bcfdb7.png)
Though that particular graph isn't as good, since the energy scale is too large and doesn't make it clear that it's a Lennard-Jones function at lambda=1.

**Comment by ppxasjsm** [comment]
I agree with the colour changes! I think a soft-core plot of some sort would be a good idea, but unsure how to visualise it. I find it difficult to understand what I am looking at in the attached plot. I'll have a think about softcore, or how to visualise this. We would have to point out that this is just one example though rather than all alchemical schemes use soft core.

**Comment by mrshirts** [comment]
Sorry if the graph is not clear.  It's a curve where U(r,lam=0) = 0, and where U(r,lam=1) = Lennard-Jones potential.  It smoothly interpolates between the two potentials.

**Comment by mrshirts** [comment]
I can work on a new version later today. . .

**Comment by ppxasjsm** [comment]
Thanks. I am likely to work on the draft on Sunday again and happy to coordinate.

**Comment by mrshirts** [comment]
See PR #40 for additional graphics.

**Comment by ppxasjsm** [comment]
[Fig2.pdf](https://github.com/michellab/alchemical-best-practices/files/3906066/Fig2.pdf)

New attempt incorporating softcore potential and colour updates.

**Comment by davidlmobley** [comment]
Overall this is looking great. I'm wondering if the bottom two panels should have inlaid cartoons showing what the energy represented is for (but maybe that's too hard). Otherwise I'm enthusiastic about this one.

**Comment by ppxasjsm** [comment]
Yeah that would be a nice idea, but lack the skills to do this in a timely fashion.
