### ISSUE TITLE
[sec:8:estimators] references

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/alchemical-best-practices#57]
@mrshirts I think I figured out most of the references in this section, but a couple eluded me. Could you please add them and just generally look over the section?

**Comment by mrshirts** [comment]
OK, added a bunch of references with overleaf.  They are all in the Zotero group 'alchemical' folder.  I have not yet updated the .bib file on Overleaf yet, since I realized we are probably using different BetterBibText citation formats.  So my citations will not have the same citations as yours. Let me know what you were using (I couldn't quite get them right) and I will correct.

**Comment by ppxasjsm** [comment]
I think just adding things to the alchemical folder is fine. I'll make sure to update the overleaf. Its probably easier than us trying to sync our BetterBibTeX versions.

**Comment by ppxasjsm** [comment]
Last I checked they all seemed fine.
