### ISSUE TITLE
all figures and their captions

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/alchemical-best-practices#67]
It would be good to check the following for all figures:
1. Are figures legible?
2. Do the figures make sense?
3. Are figure captions sufficiently descriptive?
4. Are figures mentioned in the text appropriately?

**Comment by ppxasjsm** [comment]
Particularly I would like some feedback for Fig.6. There seem to be different arrow conventions for drawing thermodynamic cycles, are there any preferences?

**Comment by davidlmobley** [comment]
I've gone through all of hte figures and made a few comments in the LaTeX. I also have these remarks:

- Figure 6: ABFE. My feeling is that the arrows don't go in the right directions. (However, seems consistent with Figure 2 directionality. I prefer arrows to form a cycle that connects the end states.) Also, should the receptor be labeled "receptor" instead of "host"?
- Figure 1A: This is a rotational invariance, not really a conformational change. Change one of the protons on the benzene ring into a chlorine to make it asymmetric so that this actually is a conformational change?? 
- Figure 3: What’s the bottom arrow connecting the left and right paths? It is not explained in the caption and I have no idea what it means.
- Figure 4: Why are some of the atoms highlighted in green and not others? Specifically, in B, shouldn’t part of the right hand ring be highlighted in green?
